"""Deterministic mapping of printed line-item labels to taxonomy keys.

Labels in Indian statements vary in numbering, wording and loss/profit phrasing ("(ii) Loss for the year
(VII-VIII)" is "Profit for the period"), and the same label means different things in different sections
("Borrowings" under non-current or current liabilities). The matcher normalises labels, compares token sets
with the taxonomy's labels and aliases, and uses the section a row sits in to pick between current and
non-current items. Rows it cannot place are reported, not guessed; an LLM mapper can take those later.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from app.domain.enums import Statement
from app.engine.catalog import Catalog, LineItem
from app.knowledge.text import stem

_ENUMERATOR = re.compile(
    r"^\s*(?:\(?[ivxlc]+\)|\(?[a-z]\)|\(?\d{1,2}\)|[IVXL]+\.?\s|[A-Z]\.|\d{1,2}\.|[-•–])\s*"
)
_TRAILING_REFERENCE = re.compile(r"\s*\((?:[IVXLA-D0-9]+\s*[+\-–]\s*)*[IVXLA-D0-9]+\)\s*$")
_PHRASES = (
    (re.compile(r"\bnon[\s-]*current\b", re.IGNORECASE), "noncurrent"),
    (
        re.compile(r"\(\s*(noncurrent|current)\s*\)", re.IGNORECASE),
        r" \1 ",
    ),  # keep qualifiers out of parentheses
    (
        re.compile(r"\bcomprehensive\s+\(?loss\)?(?:\s*/\s*\(?income\)?)?", re.IGNORECASE),
        "comprehensive income",
    ),
    (
        re.compile(r"\(?profit\)?\s*/\s*\(?loss\)?|\(?loss\)?\s*/\s*\(?profit\)?|\bloss\b", re.IGNORECASE),
        "profit",
    ),
    (re.compile(r"\b(?:period\s*/\s*year|year\s*/\s*period|year|period)\b", re.IGNORECASE), "period"),
    (re.compile(r"\bamorti[sz]ation\b", re.IGNORECASE), "amortisation"),
    (
        re.compile(
            r"\b(?:\(used in\)\s*/\s*generated from|generated from\s*/\s*\(used in\)|from\s*/\s*\(used in\)|"
            r"used in|generated from|generated by|\(used in\)|from)\b",
            re.IGNORECASE,
        ),
        " ",
    ),
    (
        re.compile(
            r"\bincrease\s*/\s*\(decrease\)|\(decrease\)\s*/\s*increase|decrease\s*/\s*increase",
            re.IGNORECASE,
        ),
        "increase decrease",
    ),
    (re.compile(r"&"), " and "),
)
_PARENTHETICAL = re.compile(r"\([^()]*\)")
_QUALIFIER_WORDS = {"noncurrent", "current"}
ACCEPT_JACCARD = 0.8  # similarity that is enough on its own
CONTAINED_JACCARD = 0.5  # similarity needed when every word of the taxonomy name appears in the label


@dataclass(frozen=True, slots=True)
class LabelMatch:
    key: str
    score: float
    matched: str  # the taxonomy label or alias that matched


def normalise(label: str) -> str:
    text = label.strip()
    while True:
        stripped = _ENUMERATOR.sub("", text, count=1)
        if stripped == text:
            break
        text = stripped
    text = _TRAILING_REFERENCE.sub("", text)
    for pattern, replacement in _PHRASES:
        text = pattern.sub(replacement, text)
    text = _PARENTHETICAL.sub(" ", text)  # asides such as "(i.e. anti-dilutive)" or "(refer note 18)"
    return " ".join(text.split())


# Only grammatical filler is ignored. Words such as "other", "before", "after" and "than" distinguish line
# items ("Other income" / "Income", "Profit before tax" / "Profit after tax"), so the retrieval stop-word list
# is not used.
_LABEL_STOP_WORDS = frozenset(
    {
        "a",
        "an",
        "the",
        "of",
        "for",
        "and",
        "to",
        "in",
        "on",
        "at",
        "by",
        "with",
        "as",
        "its",
        "their",
        "our",
        "is",
        "are",
        "be",
    }
)
_WORD = re.compile(r"[a-z0-9]+")


def _tokens(text: str) -> frozenset[str]:
    words = _WORD.findall(normalise(text).lower())
    return frozenset(stem(word) for word in words if word not in _LABEL_STOP_WORDS and not word.isdigit())


class LabelMatcher:
    def __init__(self, catalog: Catalog) -> None:
        self._names: dict[Statement, list[tuple[LineItem, str, frozenset[str]]]] = {}
        for item in catalog.items.values():
            for name in (item.label, *item.aliases):
                self._names.setdefault(item.statement, []).append((item, name, _tokens(name)))

    def match(self, label: str, statement: Statement, section: str = "") -> LabelMatch | None:
        """Best taxonomy item for a row label within its statement, or ``None`` if nothing is close enough."""
        label_tokens = _tokens(label)
        if not label_tokens:
            return None
        qualifiers = _tokens(section) & _QUALIFIER_WORDS
        # A section's current / non-current qualifier applies to its line items, not to totals ("Total
        # assets").
        qualify = qualifiers and not label_tokens & _QUALIFIER_WORDS and "total" not in label_tokens
        candidates = [label_tokens | qualifiers] if qualify else []
        candidates.append(label_tokens)

        best: tuple[tuple[int, float, int], LabelMatch] | None = None
        for rank, tokens in enumerate(candidates):
            for item, name, name_tokens in self._names.get(statement, ()):
                overlap = len(tokens & name_tokens)
                if not overlap:
                    continue
                jaccard = overlap / len(tokens | name_tokens)
                contained = name_tokens <= tokens and jaccard >= CONTAINED_JACCARD
                if jaccard < ACCEPT_JACCARD and not contained:
                    continue
                # Prefer exact matches, then qualified candidates, then higher similarity.
                order = (int(jaccard == 1.0), jaccard, -rank)
                if best is None or order > best[0]:
                    best = (order, LabelMatch(item.key, round(jaccard, 3), name))
        return best[1] if best else None
