"""rule reliability and chunk utility columns

Revision ID: acd04122d257
Revises: 382e07430a1d
Create Date: 2026-09-13 19:37:14.727292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acd04122d257"
down_revision: Union[str, Sequence[str], None] = "382e07430a1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so this is safe even if the findings table already has rows (NOT NULL columns need
    # either a default or an empty table when added to Postgres); dropped right after backfilling them.
    op.add_column(
        "findings", sa.Column("chunk_ids", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
    )
    op.alter_column("findings", "chunk_ids", server_default=None)
    op.add_column("rule_versions", sa.Column("backtest_result", sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rule_versions", "backtest_result")
    op.drop_column("findings", "chunk_ids")
    # ### end Alembic commands ###
