/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document File
         * @description The raw uploaded bytes — the evidence viewer renders a PDF-sourced fact's source page from this.
         */
        get: operations["get_document_file_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Analysis */
        post: operations["trigger_analysis_documents__document_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Analysis Events
         * @description Server-sent events with the live stage/message, polling the DB every second until a terminal status.
         *
         *     Uses its own session per poll (not the request-scoped ``SessionDep``) because that dependency's session
         *     is closed as soon as this function returns the ``StreamingResponse`` — before the generator below, which
         *     outlives the request handler, ever runs.
         */
        get: operations["stream_analysis_events_analyses__analysis_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_analyses__analysis_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/findings/{finding_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_analyses__analysis_id__findings__finding_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_rules_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/candidates/{candidate_id}/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_rules_candidates__candidate_id__backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/candidates/{candidate_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Candidate */
        post: operations["decide_candidate_rules_candidates__candidate_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/reliability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reliability */
        get: operations["reliability_rules_reliability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisDetail */
        AnalysisDetail: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Stage */
            stage: string | null;
            /** Stage Message */
            stage_message: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            report?: components["schemas"]["AnalysisReport"] | null;
        };
        /** AnalysisReport */
        AnalysisReport: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Report Id */
            report_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            company: components["schemas"]["CompanyInfo"];
            document: components["schemas"]["DocumentInfo"];
            /** Anchor Period */
            anchor_period: string;
            /** Periods */
            periods: string[];
            size_bucket: components["schemas"]["SizeBucket"] | null;
            /**
             * Overall Risk
             * @enum {string}
             */
            overall_risk: "low" | "moderate" | "elevated" | "high";
            /** Headline */
            headline: string;
            /** Executive Summary */
            executive_summary: string;
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Concerns
             * @default []
             */
            concerns: string[];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /**
             * Dismissed Rules
             * @default []
             */
            dismissed_rules: components["schemas"]["DismissedRule"][];
            /** Scorecard */
            scorecard: components["schemas"]["AreaScore"][];
            /** Integrity */
            integrity: components["schemas"]["IntegrityCheck"][];
            /** Anomalies */
            anomalies: components["schemas"]["Anomaly"][];
            /** Data Gaps */
            data_gaps: string[];
            /** Metrics */
            metrics: components["schemas"]["MetricRow"][];
            /**
             * Candidate Rules
             * @default []
             */
            candidate_rules: components["schemas"]["CandidateRule"][];
            provenance: components["schemas"]["Provenance"];
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["CallRecord"][];
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Stage */
            stage: string | null;
            /** Stage Message */
            stage_message: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** Anomaly */
        Anomaly: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Ref */
            ref: string;
            /** Period */
            period: string;
            /** Value */
            value: string;
            /** Display */
            display: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "history" | "cohort";
            /**
             * Direction
             * @enum {string}
             */
            direction: "high" | "low";
            /** Adverse */
            adverse: boolean | null;
            /** Reference */
            reference: string;
            /** Reference Display */
            reference_display: string;
            /** Score */
            score: string;
            /** Sample Size */
            sample_size: number;
        };
        /** AreaScore */
        AreaScore: {
            /** Area */
            area: string;
            /**
             * Status
             * @enum {string}
             */
            status: "concern" | "watch" | "clear" | "not_assessed";
            /** Fired */
            fired: number;
            /** Passed */
            passed: number;
            /** Insufficient */
            insufficient: number;
            worst_severity?: components["schemas"]["Severity"] | null;
        };
        /**
         * Basis
         * @enum {string}
         */
        Basis: "standalone" | "consolidated";
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /** File */
            file: string;
            /** @default other */
            sector: components["schemas"]["Sector"];
            /** Source Url */
            source_url?: string | null;
        };
        /**
         * CallRecord
         * @description One model call, kept in the analysis trace.
         */
        CallRecord: {
            /** Node */
            node: string;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Reasoning Tokens */
            reasoning_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cached */
            cached: boolean;
            /** Attempts */
            attempts: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "repaired" | "failed";
            /** Error */
            error?: string | null;
        };
        /** CandidateRule */
        CandidateRule: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            severity: components["schemas"]["Severity"];
            /** When */
            when: string;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence: string[];
            /**
             * Status
             * @default candidate
             * @constant
             */
            status: "candidate";
            /**
             * Validation Errors
             * @default []
             */
            validation_errors: string[];
        };
        /** CompanyInfo */
        CompanyInfo: {
            /** Name */
            name: string;
            sector: components["schemas"]["Sector"];
            /** Industry */
            industry?: string | null;
            /** Nse Symbol */
            nse_symbol?: string | null;
            /** Bse Code */
            bse_code?: string | null;
            /** Isin */
            isin?: string | null;
        };
        /** Critique */
        Critique: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "revise" | "reject";
            /** Reasons */
            reasons: string;
        };
        /**
         * DismissedRule
         * @description A fired rule the agent judged immaterial for this filing, with its reason.
         */
        DismissedRule: {
            /** Rule Id */
            rule_id: string;
            /** Title */
            title: string;
            /** Reason */
            reason: string;
        };
        /**
         * DocType
         * @enum {string}
         */
        DocType: "quarterly_result" | "annual_report" | "drhp" | "rhp";
        /** DocumentDetail */
        DocumentDetail: {
            /** Id */
            id: string;
            /** Company Name */
            company_name: string;
            sector: components["schemas"]["Sector"];
            doc_type: components["schemas"]["DocType"];
            basis: components["schemas"]["Basis"];
            /** Filing Date */
            filing_date: string | null;
            /** Source Url */
            source_url: string | null;
            /** Original Filename */
            original_filename: string;
            /** Periods */
            periods: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fact Count */
            fact_count: number;
            /** Dataset */
            dataset: {
                [key: string]: unknown;
            };
        };
        /** DocumentInfo */
        DocumentInfo: {
            doc_type: components["schemas"]["DocType"];
            basis: components["schemas"]["Basis"];
            /** Title */
            title: string;
            /** Filing Date */
            filing_date?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Restated
             * @default false
             */
            restated: boolean;
            /**
             * Fiscal Year End Month
             * @default 3
             */
            fiscal_year_end_month: number;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Id */
            id: string;
            /** Company Name */
            company_name: string;
            sector: components["schemas"]["Sector"];
            doc_type: components["schemas"]["DocType"];
            basis: components["schemas"]["Basis"];
            /** Filing Date */
            filing_date: string | null;
            /** Source Url */
            source_url: string | null;
            /** Original Filename */
            original_filename: string;
            /** Periods */
            periods: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            document: components["schemas"]["DocumentSummary"];
            /** Warnings */
            warnings: components["schemas"]["IngestionWarning"][];
            /** Unmapped */
            unmapped: string[];
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Ref */
            ref: string;
            /** Label */
            label: string;
            /** Display */
            display: string;
            /** Period */
            period?: string | null;
            unit?: components["schemas"]["Unit"] | null;
            /** Page */
            page?: number | null;
            /** Source */
            source?: string | null;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "confirm" | "dismiss";
            /** Reason */
            reason?: string | null;
            /** Created By */
            created_by?: string | null;
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "agent" | "rule";
            /** Title */
            title: string;
            /** Category */
            category: string;
            severity: components["schemas"]["Severity"];
            /** Confidence */
            confidence: number;
            /** Summary */
            summary: string;
            /** Analysis */
            analysis: string;
            /** Summary Template */
            summary_template: string;
            /** Analysis Template */
            analysis_template: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Rule Ids */
            rule_ids: string[];
            /**
             * Periods
             * @default []
             */
            periods: string[];
            /**
             * Knowledge
             * @default []
             */
            knowledge: components["schemas"]["KnowledgeCitation"][];
            /**
             * Benign Explanations Considered
             * @default []
             */
            benign_explanations_considered: string[];
            /**
             * Questions For Management
             * @default []
             */
            questions_for_management: string[];
            critique?: components["schemas"]["Critique"] | null;
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            /** Finding Id */
            finding_id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Severity */
            severity: string;
            /** Origin */
            origin: string;
            /** Rule Ids */
            rule_ids: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "confirmed" | "dismissed";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionWarning */
        IngestionWarning: {
            /**
             * Level
             * @enum {string}
             */
            level: "error" | "warning" | "info";
            /** Message */
            message: string;
            /** Ref */
            ref?: string | null;
        };
        /** IntegrityCheck */
        IntegrityCheck: {
            /** Rule Id */
            rule_id: string;
            /** Title */
            title: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "fired" | "passed" | "insufficient_data";
            /** Period */
            period: string;
            /** Detail */
            detail?: string | null;
        };
        /** KnowledgeCitation */
        KnowledgeCitation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document */
            document: string;
            /** Section */
            section: string;
        };
        /** MetricRow */
        MetricRow: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            unit: components["schemas"]["Unit"];
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** Provenance */
        Provenance: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "agent" | "rules_only";
            /** Catalog Version */
            catalog_version: string;
            /** Kb Version */
            kb_version: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Models */
            models: string[];
            token_usage: components["schemas"]["TokenUsage"];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** RuleCandidateOut */
        RuleCandidateOut: {
            /** Id */
            id: string;
            /** Rule Id */
            rule_id: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "candidate" | "approved" | "rejected";
            /** Source Analysis Id */
            source_analysis_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided By */
            decided_by: string | null;
            /** Decided At */
            decided_at: string | null;
            /** Backtest Result */
            backtest_result?: {
                [key: string]: unknown;
            } | null;
        };
        /** RuleDecisionIn */
        RuleDecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Decided By */
            decided_by?: string | null;
        };
        /** RuleReliability */
        RuleReliability: {
            /** Rule Id */
            rule_id: string;
            /** Confirms */
            confirms: number;
            /** Dismisses */
            dismisses: number;
            /** Score */
            score: number;
        };
        /**
         * Sector
         * @enum {string}
         */
        Sector: "banking" | "nbfc" | "insurance" | "it_services" | "manufacturing" | "infrastructure" | "pharma_healthcare" | "fmcg_consumer" | "auto" | "chemicals" | "metals_mining" | "energy_utilities" | "real_estate" | "telecom_media" | "consumer_internet" | "other";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "low" | "medium" | "high" | "critical";
        /**
         * SizeBucket
         * @description Size band by annualised revenue from operations (₹ crore).
         * @enum {string}
         */
        SizeBucket: "small" | "mid" | "large";
        /** TokenUsage */
        TokenUsage: {
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Cached Calls
             * @default 0
             */
            cached_calls: number;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "inr_crore" | "inr" | "ratio" | "times" | "days" | "count" | "text";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_file_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_analysis_documents__document_id__analyses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_analyses_get: {
        parameters: {
            query?: {
                document_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_analysis_events_analyses__analysis_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_analyses__analysis_id__findings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_analyses__analysis_id__findings__finding_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_rules_candidates_get: {
        parameters: {
            query?: {
                status_filter?: ("candidate" | "approved" | "rejected") | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_rules_candidates__candidate_id__backtest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_candidate_rules_candidates__candidate_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reliability_rules_reliability_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleReliability"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
